-- KyiSplit expected PostgreSQL schema.
-- This is a target-state reference for manual database administration.
-- It is not a migration or a safe incremental update for a populated database.

CREATE DOMAIN public.kyisplit_money AS numeric
    CHECK (
        scale(VALUE) <= 2
        AND abs(VALUE) < 10000000000000000
    );

CREATE TABLE public.users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email character varying NOT NULL UNIQUE,
    password character varying NOT NULL,
    CONSTRAINT users_email_normalized_check CHECK (
        email = lower(btrim(email))
        AND char_length(email) BETWEEN 1 AND 254
        AND email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'
    )
);

CREATE UNIQUE INDEX users_email_lower_key ON public.users (lower(email));

CREATE TABLE public.groups (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name character varying NOT NULL,
    default_currency character varying(3) NOT NULL,
    CONSTRAINT groups_name_normalized_check CHECK (
        name = btrim(name)
        AND char_length(name) BETWEEN 1 AND 100
    ),
    CONSTRAINT groups_default_currency_check CHECK (
        default_currency ~ '^[A-Z]{3}$'
    ),
    CONSTRAINT groups_id_default_currency_key UNIQUE (id, default_currency)
);

CREATE TABLE public.group_members (
    group_id uuid NOT NULL,
    user_id uuid NOT NULL,
    user_group_name character varying NOT NULL,
    PRIMARY KEY (group_id, user_id),
    CONSTRAINT group_members_name_normalized_check CHECK (
        user_group_name = btrim(user_group_name)
        AND char_length(user_group_name) BETWEEN 1 AND 50
    ),
    CONSTRAINT group_members_group_id_fkey
        FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE RESTRICT,
    CONSTRAINT group_members_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE TABLE public.invites (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id uuid NOT NULL,
    token character varying NOT NULL UNIQUE,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT invites_token_format_check CHECK (token ~ '^[0-9a-f]{64}$'),
    CONSTRAINT invites_chronology_check CHECK (expires_at > created_at),
    CONSTRAINT invites_group_id_fkey
        FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE RESTRICT,
    CONSTRAINT invites_created_by_fkey
        FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE TABLE public.expenses (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id uuid NOT NULL,
    name character varying NOT NULL,
    total public.kyisplit_money NOT NULL,
    date date NOT NULL DEFAULT now(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    currency character varying(3) NOT NULL,
    CONSTRAINT expenses_name_normalized_check CHECK (
        name = btrim(name)
        AND char_length(name) BETWEEN 1 AND 120
    ),
    CONSTRAINT expenses_total_positive_check CHECK (total > 0),
    CONSTRAINT expenses_currency_check CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT expenses_group_id_fkey
        FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE RESTRICT,
    CONSTRAINT expenses_id_group_id_key UNIQUE (id, group_id),
    CONSTRAINT expenses_id_currency_group_id_key UNIQUE (id, currency, group_id)
);

CREATE TABLE public.payments (
    expense_id uuid NOT NULL,
    user_id uuid NOT NULL,
    amount public.kyisplit_money NOT NULL,
    group_id uuid NOT NULL,
    PRIMARY KEY (expense_id, user_id),
    CONSTRAINT payments_amount_positive_check CHECK (amount > 0),
    CONSTRAINT payments_expense_group_fkey
        FOREIGN KEY (expense_id, group_id)
        REFERENCES public.expenses(id, group_id)
        ON DELETE CASCADE,
    CONSTRAINT payments_member_fkey
        FOREIGN KEY (group_id, user_id)
        REFERENCES public.group_members(group_id, user_id)
        ON DELETE RESTRICT,
    CONSTRAINT payments_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE TABLE public.splits (
    expense_id uuid NOT NULL,
    user_id uuid NOT NULL,
    amount public.kyisplit_money NOT NULL,
    group_id uuid NOT NULL,
    PRIMARY KEY (expense_id, user_id),
    CONSTRAINT splits_amount_positive_check CHECK (amount > 0),
    CONSTRAINT splits_expense_group_fkey
        FOREIGN KEY (expense_id, group_id)
        REFERENCES public.expenses(id, group_id)
        ON DELETE CASCADE,
    CONSTRAINT splits_member_fkey
        FOREIGN KEY (group_id, user_id)
        REFERENCES public.group_members(group_id, user_id)
        ON DELETE RESTRICT,
    CONSTRAINT splits_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE TABLE public.expense_fx_snapshots (
    expense_id uuid PRIMARY KEY,
    group_id uuid NOT NULL,
    source_currency character varying(3) NOT NULL,
    target_currency character varying(3) NOT NULL,
    rate numeric(24, 12) NOT NULL,
    provider character varying(100) NOT NULL,
    provider_effective_at timestamp with time zone,
    captured_at timestamp with time zone NOT NULL,
    CONSTRAINT expense_fx_expense_fkey
        FOREIGN KEY (expense_id, source_currency, group_id)
        REFERENCES public.expenses(id, currency, group_id)
        ON DELETE CASCADE,
    CONSTRAINT expense_fx_group_currency_fkey
        FOREIGN KEY (group_id, target_currency)
        REFERENCES public.groups(id, default_currency)
        ON DELETE RESTRICT,
    CONSTRAINT expense_fx_source_currency_check CHECK (
        source_currency ~ '^[A-Z]{3}$'
    ),
    CONSTRAINT expense_fx_target_currency_check CHECK (
        target_currency ~ '^[A-Z]{3}$'
    ),
    CONSTRAINT expense_fx_rate_positive_check CHECK (rate > 0),
    CONSTRAINT expense_fx_identity_rate_check CHECK (
        source_currency <> target_currency OR rate = 1
    ),
    CONSTRAINT expense_fx_provider_check CHECK (
        provider = btrim(provider)
        AND char_length(provider) BETWEEN 1 AND 100
    )
);

CREATE TABLE public.repayments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id uuid NOT NULL,
    payer_user_id uuid NOT NULL,
    receiver_user_id uuid NOT NULL,
    amount public.kyisplit_money NOT NULL,
    currency character varying(3) NOT NULL,
    repayment_date date NOT NULL,
    recorded_by_user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT repayments_distinct_members_check CHECK (
        payer_user_id <> receiver_user_id
    ),
    CONSTRAINT repayments_amount_positive_check CHECK (amount > 0),
    CONSTRAINT repayments_currency_check CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT repayments_group_currency_fkey
        FOREIGN KEY (group_id, currency)
        REFERENCES public.groups(id, default_currency)
        ON DELETE RESTRICT,
    CONSTRAINT repayments_payer_member_fkey
        FOREIGN KEY (group_id, payer_user_id)
        REFERENCES public.group_members(group_id, user_id)
        ON DELETE RESTRICT,
    CONSTRAINT repayments_receiver_member_fkey
        FOREIGN KEY (group_id, receiver_user_id)
        REFERENCES public.group_members(group_id, user_id)
        ON DELETE RESTRICT,
    CONSTRAINT repayments_recorder_member_fkey
        FOREIGN KEY (group_id, recorded_by_user_id)
        REFERENCES public.group_members(group_id, user_id)
        ON DELETE RESTRICT
);

CREATE INDEX repayments_group_order_idx
    ON public.repayments (
        group_id,
        repayment_date DESC,
        created_at DESC,
        id DESC
    );

CREATE FUNCTION public.kyisplit_assert_expense_balanced()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_ids uuid[];
    affected_id uuid;
    expense_total numeric;
    payment_total numeric;
    split_total numeric;
BEGIN
    IF TG_TABLE_NAME = 'expenses' THEN
        IF TG_OP = 'DELETE' THEN
            affected_ids := ARRAY[OLD.id];
        ELSE
            affected_ids := ARRAY[NEW.id];
        END IF;
    ELSIF TG_OP = 'INSERT' THEN
        affected_ids := ARRAY[NEW.expense_id];
    ELSIF TG_OP = 'DELETE' THEN
        affected_ids := ARRAY[OLD.expense_id];
    ELSE
        affected_ids := ARRAY[OLD.expense_id, NEW.expense_id];
    END IF;

    FOR affected_id IN SELECT DISTINCT unnest(affected_ids)
    LOOP
        SELECT
            expense.total,
            COALESCE((
                SELECT sum(payment.amount)
                FROM public.payments AS payment
                WHERE payment.expense_id = expense.id
            ), 0),
            COALESCE((
                SELECT sum(split.amount)
                FROM public.splits AS split
                WHERE split.expense_id = expense.id
            ), 0)
        INTO expense_total, payment_total, split_total
        FROM public.expenses AS expense
        WHERE expense.id = affected_id;

        IF NOT FOUND THEN
            CONTINUE;
        END IF;
        IF payment_total <> expense_total THEN
            RAISE EXCEPTION
                'Expense % payments sum % does not equal total %',
                affected_id, payment_total, expense_total;
        END IF;
        IF split_total <> expense_total THEN
            RAISE EXCEPTION
                'Expense % splits sum % does not equal total %',
                affected_id, split_total, expense_total;
        END IF;
    END LOOP;

    RETURN NULL;
END
$$;

CREATE CONSTRAINT TRIGGER expenses_balanced_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.expenses
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.kyisplit_assert_expense_balanced();

CREATE CONSTRAINT TRIGGER payments_balanced_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.payments
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.kyisplit_assert_expense_balanced();

CREATE CONSTRAINT TRIGGER splits_balanced_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.splits
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.kyisplit_assert_expense_balanced();

CREATE FUNCTION public.kyisplit_protect_expense_fx()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'Expense FX snapshot % is immutable', OLD.expense_id;
    END IF;
    IF EXISTS (
        SELECT 1 FROM public.expenses WHERE id = OLD.expense_id
    ) THEN
        RAISE EXCEPTION
            'Expense FX snapshot % is immutable while its expense exists',
            OLD.expense_id;
    END IF;
    RETURN OLD;
END
$$;

CREATE TRIGGER expense_fx_immutable_trigger
BEFORE UPDATE OR DELETE ON public.expense_fx_snapshots
FOR EACH ROW
EXECUTE FUNCTION public.kyisplit_protect_expense_fx();

CREATE FUNCTION public.kyisplit_assert_expense_has_fx()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_id uuid;
BEGIN
    IF TG_TABLE_NAME = 'expenses' THEN
        affected_id := CASE
            WHEN TG_OP = 'DELETE' THEN OLD.id
            ELSE NEW.id
        END;
    ELSE
        affected_id := CASE
            WHEN TG_OP = 'DELETE' THEN OLD.expense_id
            ELSE NEW.expense_id
        END;
    END IF;

    IF EXISTS (
        SELECT 1 FROM public.expenses WHERE id = affected_id
    ) AND NOT EXISTS (
        SELECT 1
        FROM public.expense_fx_snapshots
        WHERE expense_id = affected_id
          AND rate IS NOT NULL
          AND provider IS NOT NULL
    ) THEN
        RAISE EXCEPTION
            'Expense % is missing a finalized FX snapshot', affected_id;
    END IF;
    RETURN NULL;
END
$$;

CREATE CONSTRAINT TRIGGER expenses_require_fx_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.expenses
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.kyisplit_assert_expense_has_fx();

CREATE CONSTRAINT TRIGGER snapshots_require_fx_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.expense_fx_snapshots
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.kyisplit_assert_expense_has_fx();
